import type { INodeProperties } from 'n8n-workflow';

export const airbnbOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['airbnb'] } },
		options: [
			{
				name: 'Get Listing',
				value: 'listing',
				action: 'Get an airbnb listing',
				description:
					'Get one Airbnb listing in full: description, property and room type, capacity and room counts, the complete grouped amenity list including the ones the place does NOT have, host profile and stats, house rules with parsed check-in and check-out times, cancellation policy, sleeping arrangements, photo tour, every image, and the RATING BREAKDOWN of six category ratings, the five-bucket star distribution and the synthesised review tags. There is NO NIGHTLY PRICE on this endpoint under any parameters, with or without dates: prices are search-only. Costs 1 credit.',
				routing: { request: { method: 'POST', url: '/api/v1/airbnb/listing' } },
			},
			{
				name: 'Get Reviews',
				value: 'reviews',
				action: 'Get airbnb reviews',
				description:
					'Get Airbnb review BODIES with per-review rating, date, and reviewer name, photo and location, paged with Offset and Reviews Per Page. The response count is the total review count for the listing and returned is how many this page holds. The rating breakdown and review tags are NOT here, they live on Get Listing. Costs 1 credit.',
				routing: { request: { method: 'POST', url: '/api/v1/airbnb/reviews' } },
			},
			{
				name: 'Search Stays',
				value: 'search',
				action: 'Search airbnb stays',
				description:
					'Search Airbnb stays: stay-total and per-night price with the full discount ledger, rating and review count, bedrooms, beds and baths, coordinates, badges and images, 18 listings per page. This is the ONLY endpoint that carries prices. With no dates Airbnb prices a window 30 days out for 5 nights and A/B tests both the window and the price, so the response flags dates_are_defaulted and repeat calls can disagree. Costs 1 credit.',
				routing: { request: { method: 'POST', url: '/api/v1/airbnb/search' } },
			},
		],
		default: 'search',
	},
];

export const airbnbFields: INodeProperties[] = [
	// -- Search Stays --
	{
		displayName: 'Location',
		name: 'location',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'Lisbon, Portugal',
		displayOptions: { show: { resource: ['airbnb'], operation: ['search'] } },
		routing: { request: { body: { location: '={{ $value }}' } } },
		description:
			'City, region, ZIP, or a pasted airbnb.com/s/ URL. A location Airbnb cannot resolve comes back as a 404.',
	},

	// -- Get Listing + Get Reviews --
	{
		displayName: 'Listing ID or URL',
		name: 'listing_id',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'https://www.airbnb.com/rooms/12345678',
		displayOptions: { show: { resource: ['airbnb'], operation: ['listing', 'reviews'] } },
		routing: { request: { body: { listing_id: '={{ $value }}' } } },
		description:
			"Airbnb listing ID or a full /rooms/ URL. Query params on a pasted URL are discarded, because they carry someone else's dates.",
	},

	// -- Additional Options: Search Stays --
	{
		displayName: 'Additional Options',
		name: 'additionalOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: { resource: ['airbnb'], operation: ['search'] } },
		options: [
			{
				displayName: 'Adults',
				name: 'adults',
				type: 'number',
				default: 1,
				typeOptions: { minValue: 1 },
				description: 'Number of adults in the party',
				routing: { request: { body: { adults: '={{ $value }}' } } },
			},
			{
				displayName: 'Amenities',
				name: 'amenities',
				type: 'string',
				default: '',
				placeholder: 'wifi,pool,free_parking',
				description:
					'Comma-separated amenities to require, from wifi, air_conditioning, pool, kitchen, free_parking, washer, self_check_in and tv, or raw numeric Airbnb amenity IDs. An unrecognised name is rejected before the scrape, because Airbnb answers one with the UNFILTERED set under a 200.',
				routing: { request: { body: { amenities: '={{ $value }}' } } },
			},
			{
				displayName: 'Check-In Date',
				name: 'check_in',
				type: 'string',
				default: '',
				placeholder: '2026-09-14',
				description:
					'Start of the stay as YYYY-MM-DD. Must be sent with Check-Out Date, and with neither Airbnb picks a window 30 days out for 5 nights and A/B tests the prices.',
				routing: { request: { body: { check_in: '={{ $value }}' } } },
			},
			{
				displayName: 'Check-Out Date',
				name: 'check_out',
				type: 'string',
				default: '',
				placeholder: '2026-09-19',
				description: 'End of the stay as YYYY-MM-DD. Must be sent with Check-In Date.',
				routing: { request: { body: { check_out: '={{ $value }}' } } },
			},
			{
				displayName: 'Children',
				name: 'children',
				type: 'number',
				default: 0,
				typeOptions: { minValue: 0 },
				description: 'Number of children aged 2-12',
				routing: { request: { body: { children: '={{ $value }}' } } },
			},
			{
				displayName: 'Currency',
				name: 'currency',
				type: 'string',
				default: 'USD',
				placeholder: 'EUR',
				description:
					'ISO 4217 currency the prices come back in. Without one Airbnb prices off the proxy exit and two identical requests disagree, so the transport sends USD.',
				routing: { request: { body: { currency: '={{ $value }}' } } },
			},
			{
				displayName: 'Free Cancellation',
				name: 'free_cancellation',
				type: 'boolean',
				default: false,
				description: 'Whether to keep only listings offering free cancellation',
				routing: { request: { body: { free_cancellation: '={{ $value }}' } } },
			},
			{
				displayName: 'Guest Favorite',
				name: 'guest_favorite',
				type: 'boolean',
				default: false,
				description: 'Whether to keep only listings badged as a guest favourite',
				routing: { request: { body: { guest_favorite: '={{ $value }}' } } },
			},
			{
				displayName: 'Infants',
				name: 'infants',
				type: 'number',
				default: 0,
				typeOptions: { minValue: 0 },
				description: 'Number of infants in the party',
				routing: { request: { body: { infants: '={{ $value }}' } } },
			},
			{
				displayName: 'Instant Book',
				name: 'instant_book',
				type: 'boolean',
				default: false,
				description: 'Whether to keep only listings that can be booked instantly',
				routing: { request: { body: { instant_book: '={{ $value }}' } } },
			},
			{
				displayName: 'Max Price',
				name: 'max_price',
				type: 'number',
				default: 0,
				typeOptions: { minValue: 0 },
				description: 'Maximum WHOLE-STAY total in Currency, not a per-night rate',
				routing: { request: { body: { max_price: '={{ $value }}' } } },
			},
			{
				displayName: 'Min Bathrooms',
				name: 'min_bathrooms',
				type: 'number',
				default: 0,
				typeOptions: { minValue: 0 },
				description: 'Minimum number of bathrooms',
				routing: { request: { body: { min_bathrooms: '={{ $value }}' } } },
			},
			{
				displayName: 'Min Bedrooms',
				name: 'min_bedrooms',
				type: 'number',
				default: 0,
				typeOptions: { minValue: 0 },
				description: 'Minimum number of bedrooms',
				routing: { request: { body: { min_bedrooms: '={{ $value }}' } } },
			},
			{
				displayName: 'Min Beds',
				name: 'min_beds',
				type: 'number',
				default: 0,
				typeOptions: { minValue: 0 },
				description: 'Minimum number of beds',
				routing: { request: { body: { min_beds: '={{ $value }}' } } },
			},
			{
				displayName: 'Min Price',
				name: 'min_price',
				type: 'number',
				default: 0,
				typeOptions: { minValue: 0 },
				description: 'Minimum WHOLE-STAY total in Currency, not a per-night rate',
				routing: { request: { body: { min_price: '={{ $value }}' } } },
			},
			{
				displayName: 'Page',
				name: 'page',
				type: 'number',
				default: 1,
				typeOptions: { minValue: 1 },
				description:
					'Result page to fetch, 18 listings per page. Cannot be combined with Pagination Cursor: the API rejects a request carrying both.',
				routing: { request: { body: { page: '={{ $value }}' } } },
			},
			{
				displayName: 'Pagination Cursor',
				name: 'cursor',
				type: 'string',
				default: '',
				description:
					'The next_cursor from a previous Search Stays response. Cannot be combined with Page: the API rejects a request carrying both.',
				routing: { request: { body: { cursor: '={{ $value }}' } } },
			},
			{
				displayName: 'Pets',
				name: 'pets',
				type: 'number',
				default: 0,
				typeOptions: { minValue: 0 },
				description: 'Number of pets travelling with the party',
				routing: { request: { body: { pets: '={{ $value }}' } } },
			},
			{
				displayName: 'Room Type',
				name: 'room_type',
				type: 'options',
				default: 'entire_home',
				options: [
					{ name: 'Entire Home', value: 'entire_home' },
					{ name: 'Hotel Room', value: 'hotel_room' },
					{ name: 'Private Room', value: 'private_room' },
					{ name: 'Shared Room', value: 'shared_room' },
				],
				description:
					'Room type to keep. Only these four names are accepted, because an unrecognised value makes Airbnb return the UNFILTERED set under a 200.',
				routing: { request: { body: { room_type: '={{ $value }}' } } },
			},
			{
				displayName: 'Superhost',
				name: 'superhost',
				type: 'boolean',
				default: false,
				description: 'Whether to keep only listings hosted by a Superhost',
				routing: { request: { body: { superhost: '={{ $value }}' } } },
			},
		],
	},

	// -- Additional Options: Get Listing --
	{
		displayName: 'Additional Options',
		name: 'additionalOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: { resource: ['airbnb'], operation: ['listing'] } },
		options: [
			{
				displayName: 'Adults',
				name: 'adults',
				type: 'number',
				default: 1,
				typeOptions: { minValue: 1 },
				description: 'Number of adults the listing is read for',
				routing: { request: { body: { adults: '={{ $value }}' } } },
			},
			{
				displayName: 'Check-In Date',
				name: 'check_in',
				type: 'string',
				default: '',
				placeholder: '2026-09-14',
				description:
					'Start of the stay as YYYY-MM-DD, which sets the availability context. Must be sent with Check-Out Date, and it still returns no nightly price.',
				routing: { request: { body: { check_in: '={{ $value }}' } } },
			},
			{
				displayName: 'Check-Out Date',
				name: 'check_out',
				type: 'string',
				default: '',
				placeholder: '2026-09-19',
				description: 'End of the stay as YYYY-MM-DD. Must be sent with Check-In Date.',
				routing: { request: { body: { check_out: '={{ $value }}' } } },
			},
			{
				displayName: 'Children',
				name: 'children',
				type: 'number',
				default: 0,
				typeOptions: { minValue: 0 },
				description: 'Number of children aged 2-12',
				routing: { request: { body: { children: '={{ $value }}' } } },
			},
			{
				displayName: 'Currency',
				name: 'currency',
				type: 'string',
				default: 'USD',
				placeholder: 'EUR',
				description: 'ISO 4217 currency for the money fields the listing does carry, such as fees',
				routing: { request: { body: { currency: '={{ $value }}' } } },
			},
			{
				displayName: 'Infants',
				name: 'infants',
				type: 'number',
				default: 0,
				typeOptions: { minValue: 0 },
				description: 'Number of infants in the party',
				routing: { request: { body: { infants: '={{ $value }}' } } },
			},
			{
				displayName: 'Pets',
				name: 'pets',
				type: 'number',
				default: 0,
				typeOptions: { minValue: 0 },
				description: 'Number of pets travelling with the party',
				routing: { request: { body: { pets: '={{ $value }}' } } },
			},
		],
	},

	// -- Additional Options: Get Reviews --
	{
		displayName: 'Additional Options',
		name: 'additionalOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: { resource: ['airbnb'], operation: ['reviews'] } },
		options: [
			{
				displayName: 'Currency',
				name: 'currency',
				type: 'string',
				default: 'USD',
				placeholder: 'EUR',
				description: 'ISO 4217 currency passed through to Airbnb with the request',
				routing: { request: { body: { currency: '={{ $value }}' } } },
			},
			{
				displayName: 'Offset',
				name: 'offset',
				type: 'number',
				default: 0,
				typeOptions: { minValue: 0 },
				description: 'How many reviews to skip before this page, so page 2 of 30 starts at 30',
				routing: { request: { body: { offset: '={{ $value }}' } } },
			},
			{
				displayName: 'Reviews Per Page',
				name: 'reviewsPerPage',
				type: 'number',
				default: 30,
				typeOptions: { minValue: 1, maxValue: 50 },
				description: 'How many reviews this page holds, 1-50. The API sends 30 when unset.',
				routing: { request: { body: { limit: '={{ $value }}' } } },
			},
		],
	},
];
