import type { INodeProperties } from 'n8n-workflow';

export const googleOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['google'] } },
		options: [
			{
				name: 'AI Mode',
				value: 'aiMode',
				action: 'Search google ai mode',
				description: "Ask Google's AI Mode and return its answer blocks, references, and shopping results",
				routing: {
					request: { method: 'POST', url: '/api/v2/google/ai-mode' },
				},
			},
			{
				name: 'Flights Search',
				value: 'flightsSearch',
				action: 'Search google flights',
				description: 'Search Google Flights and return the best and other itineraries for a route',
				routing: {
					request: { method: 'POST', url: '/api/v2/google/flights' },
				},
			},
			{
				name: 'Hotels Detail',
				value: 'hotelsDetail',
				action: 'Get google hotel details',
				description: 'Get one property with its booking sources, using a detail token from Hotels Search',
				routing: {
					request: { method: 'POST', url: '/api/v2/google/hotels/detail' },
				},
			},
			{
				name: 'Hotels Search',
				value: 'hotelsSearch',
				action: 'Search google hotels',
				description: 'Search Google Hotels and return available properties with prices and ratings',
				routing: {
					request: { method: 'POST', url: '/api/v2/google/hotels' },
				},
			},
			{
				name: 'Maps Place Details',
				value: 'mapsPlace',
				action: 'Get a google maps place',
				description: 'Get full details for one Google Maps place by place ID or data CID',
				routing: {
					request: { method: 'POST', url: '/api/v2/google/maps/place' },
				},
			},
			{
				name: 'Maps Reviews',
				value: 'mapsReviews',
				action: 'Get google maps reviews',
				description: 'Get the reviews for a Google Maps place, paginated by next page token',
				routing: {
					request: { method: 'POST', url: '/api/v2/google/maps/reviews' },
				},
			},
			{
				name: 'Maps Search',
				value: 'mapsSearch',
				action: 'Search google maps',
				description: 'Search Google Maps and return local business listings with ratings, reviews, and contact details',
				routing: {
					request: { method: 'POST', url: '/api/v2/google/maps/search' },
				},
			},
			{
				name: 'News Search',
				value: 'newsSearch',
				action: 'Search google news',
				description: 'Search Google News by query, or browse a topic, section, story, publication, or entity',
				routing: {
					request: { method: 'POST', url: '/api/v2/google/news' },
				},
			},
			{
				name: 'Search',
				value: 'search',
				action: 'Search google',
				description: 'Search Google and return organic results, knowledge graph, news, and more',
				routing: {
					request: { method: 'POST', url: '/api/v2/google' },
				},
			},
			{
				name: 'Shopping Product',
				value: 'shoppingProduct',
				action: 'Get a google shopping product',
				description: 'Get one Google Shopping product with its offers and stores',
				routing: {
					request: { method: 'POST', url: '/api/v2/google/shopping/product' },
				},
			},
			{
				name: 'Shopping Product Stores',
				value: 'shoppingProductStores',
				action: 'Get google shopping product stores',
				description: 'Get the next page of stores for a Google Shopping product',
				routing: {
					request: { method: 'POST', url: '/api/v2/google/shopping/product/stores' },
				},
			},
			{
				name: 'Shopping Search',
				value: 'shoppingSearch',
				action: 'Search google shopping',
				description: 'Search Google Shopping and return product listings with prices and merchants',
				routing: {
					request: { method: 'POST', url: '/api/v2/google/shopping' },
				},
			},
			{
				name: 'Trending Now',
				value: 'trendingNow',
				action: 'Get google trending now',
				description: 'Get the currently trending searches for a country',
				routing: {
					request: { method: 'POST', url: '/api/v2/google/trending' },
				},
			},
			{
				name: 'Trends',
				value: 'trends',
				action: 'Get google trends',
				description: 'Get Google Trends interest over time and interest by region for a term',
				routing: {
					request: { method: 'POST', url: '/api/v2/google/trends' },
				},
			},
		],
		default: 'search',
	},
];

export const googleFields: INodeProperties[] = [
	// ── Shared query (search, aiMode, mapsSearch, shoppingSearch, trends) ──
	{
		displayName: 'Query',
		name: 'query',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'best running shoes 2026',
		displayOptions: {
			show: {
				resource: ['google'],
				operation: ['search', 'aiMode', 'mapsSearch', 'shoppingSearch', 'trends'],
			},
		},
		routing: { request: { body: { query: '={{ $value }}' } } },
		description: 'The search query. For Maps Search use a niche plus a place, e.g. "plumbers in Austin, TX".',
	},

	// ── Maps Place Details ──
	{
		displayName: 'Lookup By',
		name: 'placeLookup',
		type: 'options',
		noDataExpression: true,
		default: 'place_id',
		displayOptions: { show: { resource: ['google'], operation: ['mapsPlace'] } },
		options: [
			{ name: 'Data CID', value: 'data_cid' },
			{ name: 'Place ID', value: 'place_id' },
		],
		description: 'Whether to identify the place by its place ID or by its numeric data CID',
	},
	{
		displayName: 'Place ID',
		name: 'place_id',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'ChIJN1t_tDeuEmsRUsoyG83frY4',
		displayOptions: {
			show: { resource: ['google'], operation: ['mapsPlace'], placeLookup: ['place_id'] },
		},
		routing: { request: { body: { place_id: '={{ $value }}' } } },
		description: 'Google place ID, returned by Maps Search',
	},
	{
		displayName: 'Data CID',
		name: 'data_cid',
		type: 'string',
		required: true,
		default: '',
		placeholder: '6324466594394968992',
		displayOptions: {
			show: { resource: ['google'], operation: ['mapsPlace'], placeLookup: ['data_cid'] },
		},
		routing: { request: { body: { data_cid: '={{ $value }}' } } },
		description: 'Numeric Google Maps CID for the place',
	},

	// ── Maps Reviews ──
	{
		displayName: 'Lookup By',
		name: 'reviewsLookup',
		type: 'options',
		noDataExpression: true,
		default: 'data_id',
		displayOptions: { show: { resource: ['google'], operation: ['mapsReviews'] } },
		options: [
			{ name: 'Data ID', value: 'data_id' },
			{ name: 'Place ID', value: 'place_id' },
		],
		description: 'Whether to identify the place by its data ID or by its place ID',
	},
	{
		displayName: 'Data ID',
		name: 'data_id',
		type: 'string',
		required: true,
		default: '',
		placeholder: '0x89c259606c152b2d:0xe230af1b18e542a7',
		displayOptions: {
			show: { resource: ['google'], operation: ['mapsReviews'], reviewsLookup: ['data_id'] },
		},
		routing: { request: { body: { data_id: '={{ $value }}' } } },
		description: 'Maps data ID in 0xHEX:0xHEX form, returned by Maps Search',
	},
	{
		displayName: 'Place ID',
		name: 'place_id',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'ChIJN1t_tDeuEmsRUsoyG83frY4',
		displayOptions: {
			show: { resource: ['google'], operation: ['mapsReviews'], reviewsLookup: ['place_id'] },
		},
		routing: { request: { body: { place_id: '={{ $value }}' } } },
		description: 'Google place ID, returned by Maps Search',
	},

	// ── Shopping Product ──
	{
		displayName: 'Lookup By',
		name: 'shoppingProductLookup',
		type: 'options',
		noDataExpression: true,
		default: 'product_id',
		displayOptions: { show: { resource: ['google'], operation: ['shoppingProduct'] } },
		options: [
			{ name: 'Catalog ID', value: 'catalog_id' },
			{ name: 'Page Token', value: 'page_token' },
			{ name: 'Product ID', value: 'product_id' },
		],
		description: 'Which identifier from a Shopping Search result to resolve the product with',
	},
	{
		displayName: 'Product ID',
		name: 'product_id',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['google'],
				operation: ['shoppingProduct'],
				shoppingProductLookup: ['product_id'],
			},
		},
		routing: { request: { body: { product_id: '={{ $value }}' } } },
		description: 'Google Shopping product ID from a Shopping Search result',
	},
	{
		displayName: 'Catalog ID',
		name: 'catalog_id',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['google'],
				operation: ['shoppingProduct'],
				shoppingProductLookup: ['catalog_id'],
			},
		},
		routing: { request: { body: { catalog_id: '={{ $value }}' } } },
		description: 'Durable catalog ID from a Shopping Search result. Query is required alongside it.',
	},
	{
		displayName: 'Query',
		name: 'query',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'sony wh-1000xm5',
		displayOptions: {
			show: {
				resource: ['google'],
				operation: ['shoppingProduct'],
				shoppingProductLookup: ['catalog_id'],
			},
		},
		routing: { request: { body: { query: '={{ $value }}' } } },
		description: 'The search term the catalog ID came from. Required whenever Catalog ID is used.',
	},
	{
		displayName: 'Page Token',
		name: 'page_token',
		type: 'string',
		typeOptions: { password: true },
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['google'],
				operation: ['shoppingProduct'],
				shoppingProductLookup: ['page_token'],
			},
		},
		routing: { request: { body: { page_token: '={{ $value }}' } } },
		description: 'Immersive product page token from a Shopping Search result',
	},

	// ── Shopping Product Stores ──
	{
		displayName: 'Catalog ID',
		name: 'catalog_id',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['google'], operation: ['shoppingProductStores'] } },
		routing: { request: { body: { catalog_id: '={{ $value }}' } } },
		description: 'The same catalog ID used on the Shopping Product call',
	},
	{
		displayName: 'Next Page Token',
		name: 'next_page_token',
		type: 'string',
		typeOptions: { password: true },
		required: true,
		default: '',
		displayOptions: { show: { resource: ['google'], operation: ['shoppingProductStores'] } },
		routing: { request: { body: { next_page_token: '={{ $value }}' } } },
		description: 'Continuation token returned by a previous Shopping Product or Stores response',
	},

	// ── Flights Search ──
	{
		displayName: 'Departure ID',
		name: 'departure_id',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'JFK',
		displayOptions: { show: { resource: ['google'], operation: ['flightsSearch'] } },
		routing: { request: { body: { departure_id: '={{ $value }}' } } },
		description: 'Origin airport IATA code. Comma-separate several codes to search more than one.',
	},
	{
		displayName: 'Arrival ID',
		name: 'arrival_id',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'LHR',
		displayOptions: { show: { resource: ['google'], operation: ['flightsSearch'] } },
		routing: { request: { body: { arrival_id: '={{ $value }}' } } },
		description: 'Destination airport IATA code. Comma-separate several codes to search more than one.',
	},
	{
		displayName: 'Outbound Date',
		name: 'outbound_date',
		type: 'string',
		required: true,
		default: '',
		placeholder: '2026-09-14',
		displayOptions: { show: { resource: ['google'], operation: ['flightsSearch'] } },
		routing: { request: { body: { outbound_date: '={{ $value }}' } } },
		description: 'Departure date in YYYY-MM-DD form',
	},

	// ── Hotels Search ──
	{
		displayName: 'Query',
		name: 'query',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'Lisbon hotels',
		displayOptions: { show: { resource: ['google'], operation: ['hotelsSearch'] } },
		routing: { request: { body: { query: '={{ $value }}' } } },
		description: 'Where to look for stays, best given as "&lt;City&gt; hotels"',
	},

	// ── Hotels Detail ──
	{
		displayName: 'Detail Token',
		name: 'detail_token',
		type: 'string',
		typeOptions: { password: true },
		required: true,
		default: '',
		displayOptions: { show: { resource: ['google'], operation: ['hotelsDetail'] } },
		routing: { request: { body: { detail_token: '={{ $value }}' } } },
		description: 'The detail_token of a property returned by Hotels Search',
	},

	// ── Shared stay dates (hotelsSearch, hotelsDetail) ──
	{
		displayName: 'Check-In Date',
		name: 'check_in_date',
		type: 'string',
		required: true,
		default: '',
		placeholder: '2026-09-14',
		displayOptions: {
			show: { resource: ['google'], operation: ['hotelsSearch', 'hotelsDetail'] },
		},
		routing: { request: { body: { check_in_date: '={{ $value }}' } } },
		description: 'Check-in date in YYYY-MM-DD form. Detail calls must repeat the dates of the search.',
	},
	{
		displayName: 'Check-Out Date',
		name: 'check_out_date',
		type: 'string',
		required: true,
		default: '',
		placeholder: '2026-09-17',
		displayOptions: {
			show: { resource: ['google'], operation: ['hotelsSearch', 'hotelsDetail'] },
		},
		routing: { request: { body: { check_out_date: '={{ $value }}' } } },
		description: 'Check-out date in YYYY-MM-DD form. Detail calls must repeat the dates of the search.',
	},

	// ── News Search ──
	{
		displayName: 'Search By',
		name: 'newsDriver',
		type: 'options',
		noDataExpression: true,
		default: 'query',
		displayOptions: { show: { resource: ['google'], operation: ['newsSearch'] } },
		options: [
			{ name: 'Entity (KGMID)', value: 'kgmid' },
			{ name: 'Publication Token', value: 'publication_token' },
			{ name: 'Query', value: 'query' },
			{ name: 'Section Token', value: 'section_token' },
			{ name: 'Story Token', value: 'story_token' },
			{ name: 'Topic Token', value: 'topic_token' },
		],
		description: 'Google News accepts exactly one of these per call, never two',
	},
	{
		displayName: 'Query',
		name: 'query',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'ai regulation',
		displayOptions: {
			show: { resource: ['google'], operation: ['newsSearch'], newsDriver: ['query'] },
		},
		routing: { request: { body: { query: '={{ $value }}' } } },
		description: 'News search query',
	},
	{
		displayName: 'Topic Token',
		name: 'topic_token',
		type: 'string',
		typeOptions: { password: true },
		required: true,
		default: '',
		displayOptions: {
			show: { resource: ['google'], operation: ['newsSearch'], newsDriver: ['topic_token'] },
		},
		routing: { request: { body: { topic_token: '={{ $value }}' } } },
		description: 'Topic token from a previous News response',
	},
	{
		displayName: 'Section Token',
		name: 'section_token',
		type: 'string',
		typeOptions: { password: true },
		required: true,
		default: '',
		displayOptions: {
			show: { resource: ['google'], operation: ['newsSearch'], newsDriver: ['section_token'] },
		},
		routing: { request: { body: { section_token: '={{ $value }}' } } },
		description: 'Section token from a previous News response',
	},
	{
		displayName: 'Story Token',
		name: 'story_token',
		type: 'string',
		typeOptions: { password: true },
		required: true,
		default: '',
		displayOptions: {
			show: { resource: ['google'], operation: ['newsSearch'], newsDriver: ['story_token'] },
		},
		routing: { request: { body: { story_token: '={{ $value }}' } } },
		description: 'Story token from a previous News response',
	},
	{
		displayName: 'Publication Token',
		name: 'publication_token',
		type: 'string',
		typeOptions: { password: true },
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['google'],
				operation: ['newsSearch'],
				newsDriver: ['publication_token'],
			},
		},
		routing: { request: { body: { publication_token: '={{ $value }}' } } },
		description: 'Publication token from a previous News response',
	},
	{
		displayName: 'KGMID',
		name: 'kgmid',
		type: 'string',
		required: true,
		default: '',
		placeholder: '/m/02_286',
		displayOptions: {
			show: { resource: ['google'], operation: ['newsSearch'], newsDriver: ['kgmid'] },
		},
		routing: { request: { body: { kgmid: '={{ $value }}' } } },
		description: 'Knowledge Graph entity ID to follow news for',
	},

	// ── Trending Now ──
	{
		displayName: 'Geo',
		name: 'geo',
		type: 'string',
		required: true,
		default: 'US',
		placeholder: 'US',
		displayOptions: { show: { resource: ['google'], operation: ['trendingNow'] } },
		routing: { request: { body: { geo: '={{ $value }}' } } },
		description: 'Uppercase country code to read trending searches for, e.g. US, GB, DE',
	},

	// ── Additional Options: Search ──
	{
		displayName: 'Additional Options',
		name: 'additionalOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: { resource: ['google'], operation: ['search'] } },
		options: [
			{
				displayName: 'Country Code',
				name: 'gl',
				type: 'string',
				default: 'us',
				description: 'ISO 3166-1 alpha-2 country code (e.g. us, gb, fr)',
				routing: { request: { body: { gl: '={{ $value }}' } } },
			},
			{
				displayName: 'Device',
				name: 'device',
				type: 'options',
				default: 'desktop',
				options: [
					{ name: 'Desktop', value: 'desktop' },
					{ name: 'Mobile', value: 'mobile' },
				],
				routing: { request: { body: { device: '={{ $value }}' } } },
			},
			{
				displayName: 'Google Domain',
				name: 'google_domain',
				type: 'string',
				default: 'google.com',
				description: 'Regional Google domain (e.g. google.com, google.de)',
				routing: { request: { body: { google_domain: '={{ $value }}' } } },
			},
			{
				displayName: 'Language',
				name: 'hl',
				type: 'string',
				default: 'en',
				description: 'UI language code (e.g. en, fr, de)',
				routing: { request: { body: { hl: '={{ $value }}' } } },
			},
			{
				displayName: 'Location',
				name: 'location',
				type: 'string',
				default: '',
				placeholder: 'New York,New York,United States',
				description: 'Canonical location name the search originates from',
				routing: { request: { body: { location: '={{ $value }}' } } },
			},
			{
				displayName: 'Page',
				name: 'page',
				type: 'number',
				default: 1,
				typeOptions: { minValue: 1, maxValue: 100 },
				description: 'Page number, 1-indexed',
				routing: { request: { body: { start: '={{ ($value - 1) * 10 }}' } } },
			},
			{
				displayName: 'Resolve AI Overview',
				name: 'resolve_ai_overview',
				type: 'boolean',
				default: true,
				description:
					'Whether to make the follow-up call and inline the full AI Overview when Google defers it. Enabled by default; turn off to skip that extra upstream request.',
				routing: { request: { body: { resolve_ai_overview: '={{ $value }}' } } },
			},
			{
				displayName: 'Time Period',
				name: 'time_period',
				type: 'options',
				default: 'last_month',
				description: 'Restrict results to a recency window',
				options: [
					{ name: 'Last Day', value: 'last_day' },
					{ name: 'Last Hour', value: 'last_hour' },
					{ name: 'Last Month', value: 'last_month' },
					{ name: 'Last Week', value: 'last_week' },
					{ name: 'Last Year', value: 'last_year' },
				],
				routing: { request: { body: { time_period: '={{ $value }}' } } },
			},
		],
	},

	// ── Additional Options: AI Mode ──
	{
		displayName: 'Additional Options',
		name: 'additionalOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: { resource: ['google'], operation: ['aiMode'] } },
		options: [
			{
				displayName: 'Country Code',
				name: 'gl',
				type: 'string',
				default: 'us',
				description: 'ISO 3166-1 alpha-2 country code (e.g. us, gb, fr)',
				routing: { request: { body: { gl: '={{ $value }}' } } },
			},
			{
				displayName: 'Device',
				name: 'device',
				type: 'options',
				default: 'desktop',
				options: [
					{ name: 'Desktop', value: 'desktop' },
					{ name: 'Mobile', value: 'mobile' },
				],
				routing: { request: { body: { device: '={{ $value }}' } } },
			},
			{
				displayName: 'Google Domain',
				name: 'google_domain',
				type: 'string',
				default: 'google.com',
				description: 'Regional Google domain (e.g. google.com, google.de)',
				routing: { request: { body: { google_domain: '={{ $value }}' } } },
			},
			{
				displayName: 'Language',
				name: 'hl',
				type: 'string',
				default: 'en',
				description: 'UI language code (e.g. en, fr, de)',
				routing: { request: { body: { hl: '={{ $value }}' } } },
			},
			{
				displayName: 'Location',
				name: 'location',
				type: 'string',
				default: '',
				placeholder: 'New York,New York,United States',
				description: 'Canonical location name the search originates from',
				routing: { request: { body: { location: '={{ $value }}' } } },
			},
			{
				displayName: 'Safe Search',
				name: 'safe',
				type: 'options',
				default: 'active',
				description: 'Filter adult content out of the results',
				options: [{ name: 'Active', value: 'active' }],
				routing: { request: { body: { safe: '={{ $value }}' } } },
			},
		],
	},

	// ── Additional Options: Maps Search ──
	{
		displayName: 'Additional Options',
		name: 'additionalOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: { resource: ['google'], operation: ['mapsSearch'] } },
		options: [
			{
				displayName: 'Country Code',
				name: 'gl',
				type: 'string',
				default: 'us',
				description: 'ISO 3166-1 alpha-2 country code (e.g. us, gb, fr)',
				routing: { request: { body: { gl: '={{ $value }}' } } },
			},
			{
				displayName: 'Google Domain',
				name: 'google_domain',
				type: 'string',
				default: 'google.com',
				description: 'Regional Google domain (e.g. google.com, google.de)',
				routing: { request: { body: { google_domain: '={{ $value }}' } } },
			},
			{
				displayName: 'Language',
				name: 'hl',
				type: 'string',
				default: 'en',
				description: 'UI language code (e.g. en, fr, de)',
				routing: { request: { body: { hl: '={{ $value }}' } } },
			},
			{
				displayName: 'Map Center',
				name: 'll',
				type: 'string',
				default: '',
				placeholder: '@30.2672,-97.7431,12z',
				description:
					'Map center as @lat,lng,zoomz. This, not Country Code, controls where results come from. Leave empty to default to the country centre.',
				routing: { request: { body: { ll: '={{ $value }}' } } },
			},
			{
				displayName: 'Start Offset',
				name: 'start',
				type: 'number',
				default: 0,
				typeOptions: { minValue: 0 },
				description: 'Result offset, in multiples of 20 (0, 20, 40, ...)',
				routing: { request: { body: { start: '={{ $value }}' } } },
			},
		],
	},

	// ── Additional Options: Maps Reviews ──
	{
		displayName: 'Additional Options',
		name: 'additionalOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: { resource: ['google'], operation: ['mapsReviews'] } },
		options: [
			{
				displayName: 'Country Code',
				name: 'gl',
				type: 'string',
				default: 'us',
				description: 'ISO 3166-1 alpha-2 country code (e.g. us, gb, fr)',
				routing: { request: { body: { gl: '={{ $value }}' } } },
			},
			{
				displayName: 'Google Domain',
				name: 'google_domain',
				type: 'string',
				default: 'google.com',
				description: 'Regional Google domain (e.g. google.com, google.de)',
				routing: { request: { body: { google_domain: '={{ $value }}' } } },
			},
			{
				displayName: 'Language',
				name: 'hl',
				type: 'string',
				default: 'en',
				description: 'UI language code (e.g. en, fr, de)',
				routing: { request: { body: { hl: '={{ $value }}' } } },
			},
			{
				displayName: 'Next Page Token',
				name: 'next_page_token',
				type: 'string',
				typeOptions: { password: true },
				default: '',
				description: 'Cursor from a previous Maps Reviews response',
				routing: { request: { body: { next_page_token: '={{ $value }}' } } },
			},
			{
				displayName: 'Reviews Per Page',
				name: 'num',
				type: 'number',
				default: 20,
				typeOptions: { minValue: 1, maxValue: 20 },
				description: 'Number of reviews to return (1-20)',
				routing: { request: { body: { num: '={{ $value }}' } } },
			},
			{
				displayName: 'Sort By',
				name: 'sort_by',
				type: 'options',
				default: 'relevance',
				options: [
					{ name: 'Highest Rating', value: 'highest_rating' },
					{ name: 'Lowest Rating', value: 'lowest_rating' },
					{ name: 'Newest', value: 'newest' },
					{ name: 'Relevance', value: 'relevance' },
				],
				routing: { request: { body: { sort_by: '={{ $value }}' } } },
			},
		],
	},

	// ── Additional Options: Shopping Search ──
	{
		displayName: 'Additional Options',
		name: 'additionalOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: { resource: ['google'], operation: ['shoppingSearch'] } },
		options: [
			{
				displayName: 'Country Code',
				name: 'gl',
				type: 'string',
				default: 'us',
				description: 'ISO 3166-1 alpha-2 country code (e.g. us, gb, fr)',
				routing: { request: { body: { gl: '={{ $value }}' } } },
			},
			{
				displayName: 'Device',
				name: 'device',
				type: 'options',
				default: 'desktop',
				options: [
					{ name: 'Desktop', value: 'desktop' },
					{ name: 'Mobile', value: 'mobile' },
				],
				routing: { request: { body: { device: '={{ $value }}' } } },
			},
			{
				displayName: 'Filter Token',
				name: 'shoprs',
				type: 'string',
				default: '',
				description: 'Opaque shoprs token lifted from filters or carousel_filters in a previous response',
				routing: { request: { body: { shoprs: '={{ $value }}' } } },
			},
			{
				displayName: 'Free Shipping',
				name: 'free_shipping',
				type: 'boolean',
				default: false,
				description: 'Whether to keep only offers that ship for free',
				routing: { request: { body: { free_shipping: '={{ $value }}' } } },
			},
			{
				displayName: 'Google Domain',
				name: 'google_domain',
				type: 'string',
				default: 'google.com',
				description: 'Regional Google domain (e.g. google.com, google.de)',
				routing: { request: { body: { google_domain: '={{ $value }}' } } },
			},
			{
				displayName: 'Language',
				name: 'hl',
				type: 'string',
				default: 'en',
				description: 'UI language code (e.g. en, fr, de)',
				routing: { request: { body: { hl: '={{ $value }}' } } },
			},
			{
				displayName: 'Location',
				name: 'location',
				type: 'string',
				default: '',
				placeholder: 'New York,New York,United States',
				description: 'Canonical location name the search originates from',
				routing: { request: { body: { location: '={{ $value }}' } } },
			},
			{
				displayName: 'Max Price',
				name: 'max_price',
				type: 'number',
				default: 0,
				typeOptions: { minValue: 0 },
				description: 'Maximum price filter',
				routing: { request: { body: { max_price: '={{ $value }}' } } },
			},
			{
				displayName: 'Min Price',
				name: 'min_price',
				type: 'number',
				default: 0,
				typeOptions: { minValue: 0 },
				description: 'Minimum price filter',
				routing: { request: { body: { min_price: '={{ $value }}' } } },
			},
			{
				displayName: 'On Sale',
				name: 'on_sale',
				type: 'boolean',
				default: false,
				description: 'Whether to keep only discounted offers',
				routing: { request: { body: { on_sale: '={{ $value }}' } } },
			},
			{
				displayName: 'Sort By',
				name: 'sort_by',
				type: 'options',
				default: 0,
				options: [
					{ name: 'Relevance', value: 0 },
					{ name: 'Price: Low to High', value: 1 },
					{ name: 'Price: High to Low', value: 2 },
				],
				routing: { request: { body: { sort_by: '={{ $value }}' } } },
			},
			{
				displayName: 'Start Offset',
				name: 'start',
				type: 'number',
				default: 0,
				typeOptions: { minValue: 0 },
				description: 'Result offset, follow pagination.next from a previous response',
				routing: { request: { body: { start: '={{ $value }}' } } },
			},
			{
				displayName: 'UULE',
				name: 'uule',
				type: 'string',
				default: '',
				description: 'Pre-encoded UULE location string, takes priority over Location',
				routing: { request: { body: { uule: '={{ $value }}' } } },
			},
		],
	},

	// ── Additional Options: Shopping Product ──
	{
		displayName: 'Additional Options',
		name: 'additionalOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: { resource: ['google'], operation: ['shoppingProduct'] } },
		options: [
			{
				displayName: 'Country Code',
				name: 'gl',
				type: 'string',
				default: 'us',
				description: 'ISO 3166-1 alpha-2 country code (e.g. us, gb, fr)',
				routing: { request: { body: { gl: '={{ $value }}' } } },
			},
			{
				displayName: 'Device',
				name: 'device',
				type: 'options',
				default: 'desktop',
				options: [
					{ name: 'Desktop', value: 'desktop' },
					{ name: 'Mobile', value: 'mobile' },
					{ name: 'Tablet', value: 'tablet' },
				],
				routing: { request: { body: { device: '={{ $value }}' } } },
			},
			{
				displayName: 'Google Domain',
				name: 'google_domain',
				type: 'string',
				default: 'google.com',
				description: 'Regional Google domain (e.g. google.com, google.de)',
				routing: { request: { body: { google_domain: '={{ $value }}' } } },
			},
			{
				displayName: 'Language',
				name: 'hl',
				type: 'string',
				default: 'en',
				description: 'UI language code (e.g. en, fr, de)',
				routing: { request: { body: { hl: '={{ $value }}' } } },
			},
			{
				displayName: 'Load All Stores',
				name: 'load_all_stores',
				type: 'boolean',
				default: false,
				description: 'Whether to pull every store offer instead of the first page',
				routing: { request: { body: { load_all_stores: '={{ $value }}' } } },
			},
			{
				displayName: 'Location',
				name: 'location',
				type: 'string',
				default: '',
				placeholder: 'New York,New York,United States',
				description: 'Canonical location name the search originates from',
				routing: { request: { body: { location: '={{ $value }}' } } },
			},
			{
				displayName: 'More Stores',
				name: 'more_stores',
				type: 'boolean',
				default: false,
				description: 'Whether to expand the store list beyond the default set',
				routing: { request: { body: { more_stores: '={{ $value }}' } } },
			},
			{
				displayName: 'Sort By',
				name: 'sort_by',
				type: 'options',
				default: 'total_price',
				description: 'Order of the seller list',
				options: [
					{ name: 'Base Price', value: 'base_price' },
					{ name: 'Promotion', value: 'promotion' },
					{ name: 'Seller Rating', value: 'seller_rating' },
					{ name: 'Total Price', value: 'total_price' },
				],
				routing: { request: { body: { sort_by: '={{ $value }}' } } },
			},
			{
				displayName: 'UULE',
				name: 'uule',
				type: 'string',
				default: '',
				description: 'Pre-encoded UULE location string, takes priority over Location',
				routing: { request: { body: { uule: '={{ $value }}' } } },
			},
		],
	},

	// ── Additional Options: Flights Search ──
	{
		displayName: 'Additional Options',
		name: 'additionalOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: { resource: ['google'], operation: ['flightsSearch'] } },
		options: [
			{
				displayName: 'Adults',
				name: 'adults',
				type: 'number',
				default: 1,
				typeOptions: { minValue: 1, maxValue: 9 },
				description: 'Number of adult passengers (1-9)',
				routing: { request: { body: { adults: '={{ $value }}' } } },
			},
			{
				displayName: 'Children',
				name: 'children',
				type: 'number',
				default: 0,
				typeOptions: { minValue: 0, maxValue: 9 },
				description: 'Number of child passengers (0-9)',
				routing: { request: { body: { children: '={{ $value }}' } } },
			},
			{
				displayName: 'Country Code',
				name: 'gl',
				type: 'string',
				default: 'us',
				description: 'ISO 3166-1 alpha-2 country code (e.g. us, gb, fr)',
				routing: { request: { body: { gl: '={{ $value }}' } } },
			},
			{
				displayName: 'Currency',
				name: 'currency',
				type: 'string',
				default: 'USD',
				description: 'Three-letter currency code prices are returned in',
				routing: { request: { body: { currency: '={{ $value }}' } } },
			},
			{
				displayName: 'Exclude Airlines',
				name: 'exclude_airlines',
				type: 'string',
				default: '',
				placeholder: 'RY,U2',
				description: 'Comma-separated airline codes to drop from the results',
				routing: { request: { body: { exclude_airlines: '={{ $value }}' } } },
			},
			{
				displayName: 'Include Airlines',
				name: 'include_airlines',
				type: 'string',
				default: '',
				placeholder: 'BA,AA',
				description: 'Comma-separated airline codes to restrict the results to',
				routing: { request: { body: { include_airlines: '={{ $value }}' } } },
			},
			{
				displayName: 'Infants in Seat',
				name: 'infants_in_seat',
				type: 'number',
				default: 0,
				typeOptions: { minValue: 0, maxValue: 4 },
				description: 'Number of infants with their own seat (0-4)',
				routing: { request: { body: { infants_in_seat: '={{ $value }}' } } },
			},
			{
				displayName: 'Infants on Lap',
				name: 'infants_on_lap',
				type: 'number',
				default: 0,
				typeOptions: { minValue: 0, maxValue: 4 },
				description: 'Number of infants travelling on a lap (0-4)',
				routing: { request: { body: { infants_on_lap: '={{ $value }}' } } },
			},
			{
				displayName: 'Language',
				name: 'hl',
				type: 'string',
				default: 'en',
				description: 'UI language code (e.g. en, fr, de)',
				routing: { request: { body: { hl: '={{ $value }}' } } },
			},
			{
				displayName: 'Return Date',
				name: 'return_date',
				type: 'string',
				default: '',
				placeholder: '2026-09-21',
				description: 'Return date in YYYY-MM-DD form. Required when Trip Type is Round Trip.',
				routing: { request: { body: { return_date: '={{ $value }}' } } },
			},
			{
				displayName: 'Sort By',
				name: 'sort_by',
				type: 'options',
				default: 1,
				options: [
					{ name: 'Arrival Time', value: 4 },
					{ name: 'Departure Time', value: 3 },
					{ name: 'Duration', value: 5 },
					{ name: 'Emissions', value: 6 },
					{ name: 'Price', value: 2 },
					{ name: 'Top Flights', value: 1 },
				],
				routing: { request: { body: { sort_by: '={{ $value }}' } } },
			},
			{
				displayName: 'Stops',
				name: 'stops',
				type: 'options',
				default: 0,
				options: [
					{ name: 'Any', value: 0 },
					{ name: 'Nonstop Only', value: 1 },
					{ name: '1 Stop or Fewer', value: 2 },
					{ name: '2 Stops or Fewer', value: 3 },
				],
				routing: { request: { body: { stops: '={{ $value }}' } } },
			},
			{
				displayName: 'Travel Class',
				name: 'travel_class',
				type: 'options',
				default: 1,
				options: [
					{ name: 'Economy', value: 1 },
					{ name: 'Premium Economy', value: 2 },
					{ name: 'Business', value: 3 },
					{ name: 'First', value: 4 },
				],
				routing: { request: { body: { travel_class: '={{ $value }}' } } },
			},
			{
				displayName: 'Trip Type',
				name: 'type',
				type: 'options',
				default: 2,
				options: [
					{ name: 'Round Trip', value: 1 },
					{ name: 'One Way', value: 2 },
					{ name: 'Multi-City', value: 3 },
				],
				routing: { request: { body: { type: '={{ $value }}' } } },
			},
		],
	},

	// ── Additional Options: Hotels Search ──
	{
		displayName: 'Additional Options',
		name: 'additionalOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: { resource: ['google'], operation: ['hotelsSearch'] } },
		options: [
			{
				displayName: 'Amenities',
				name: 'amenities',
				type: 'string',
				default: '',
				description: 'Comma-separated amenity IDs to filter on',
				routing: { request: { body: { amenities: '={{ $value }}' } } },
			},
			{
				displayName: 'Country Code',
				name: 'gl',
				type: 'string',
				default: 'us',
				description: 'ISO 3166-1 alpha-2 country code (e.g. us, gb, fr)',
				routing: { request: { body: { gl: '={{ $value }}' } } },
			},
			{
				displayName: 'Currency',
				name: 'currency',
				type: 'string',
				default: 'USD',
				description: 'Three-letter currency code prices are returned in',
				routing: { request: { body: { currency: '={{ $value }}' } } },
			},
			{
				displayName: 'Eco Certified',
				name: 'eco_certified',
				type: 'boolean',
				default: false,
				description: 'Whether to keep only eco-certified properties',
				routing: { request: { body: { eco_certified: '={{ $value }}' } } },
			},
			{
				displayName: 'Free Cancellation',
				name: 'free_cancellation',
				type: 'boolean',
				default: false,
				description: 'Whether to keep only rates with free cancellation',
				routing: { request: { body: { free_cancellation: '={{ $value }}' } } },
			},
			{
				displayName: 'Hotel Class',
				name: 'hotel_class',
				type: 'string',
				default: '',
				placeholder: '4,5',
				description: 'Comma-separated star ratings from 2 to 5',
				routing: { request: { body: { hotel_class: '={{ $value }}' } } },
			},
			{
				displayName: 'Language',
				name: 'hl',
				type: 'string',
				default: 'en',
				description: 'UI language code (e.g. en, fr, de)',
				routing: { request: { body: { hl: '={{ $value }}' } } },
			},
			{
				displayName: 'Max Price',
				name: 'max_price',
				type: 'number',
				default: 0,
				typeOptions: { minValue: 0 },
				description: 'Maximum nightly price',
				routing: { request: { body: { max_price: '={{ $value }}' } } },
			},
			{
				displayName: 'Min Price',
				name: 'min_price',
				type: 'number',
				default: 0,
				typeOptions: { minValue: 0 },
				description: 'Minimum nightly price',
				routing: { request: { body: { min_price: '={{ $value }}' } } },
			},
			{
				displayName: 'Next Page Token',
				name: 'next_page_token',
				type: 'string',
				typeOptions: { password: true },
				default: '',
				description: 'Cursor from a previous Hotels Search response',
				routing: { request: { body: { next_page_token: '={{ $value }}' } } },
			},
			{
				displayName: 'Properties Per Page',
				name: 'propertiesPerPage',
				type: 'number',
				default: 20,
				typeOptions: { minValue: 1, maxValue: 20 },
				description: 'Number of properties to return (1-20)',
				routing: { request: { body: { limit: '={{ $value }}' } } },
			},
			{
				displayName: 'Property Types',
				name: 'property_types',
				type: 'string',
				default: '',
				placeholder: '12',
				description: 'Comma-separated property type IDs, 12 is vacation rentals',
				routing: { request: { body: { property_types: '={{ $value }}' } } },
			},
			{
				displayName: 'Rating',
				name: 'rating',
				type: 'options',
				default: 8,
				description: 'Minimum guest rating',
				options: [
					{ name: '3.5 and Up', value: 7 },
					{ name: '4.0 and Up', value: 8 },
					{ name: '4.5 and Up', value: 9 },
				],
				routing: { request: { body: { rating: '={{ $value }}' } } },
			},
			{
				displayName: 'Sort By',
				name: 'sort_by',
				type: 'options',
				default: 3,
				options: [
					{ name: 'Lowest Price', value: 3 },
					{ name: 'Highest Rating', value: 8 },
					{ name: 'Most Reviewed', value: 13 },
				],
				routing: { request: { body: { sort_by: '={{ $value }}' } } },
			},
			{
				displayName: 'Special Offers',
				name: 'special_offers',
				type: 'boolean',
				default: false,
				description: 'Whether to keep only properties running a special offer',
				routing: { request: { body: { special_offers: '={{ $value }}' } } },
			},
		],
	},

	// ── Additional Options: Hotels Detail ──
	{
		displayName: 'Additional Options',
		name: 'additionalOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: { resource: ['google'], operation: ['hotelsDetail'] } },
		options: [
			{
				displayName: 'Country Code',
				name: 'gl',
				type: 'string',
				default: 'us',
				description: 'ISO 3166-1 alpha-2 country code (e.g. us, gb, fr)',
				routing: { request: { body: { gl: '={{ $value }}' } } },
			},
			{
				displayName: 'Currency',
				name: 'currency',
				type: 'string',
				default: 'USD',
				description: 'Three-letter currency code prices are returned in',
				routing: { request: { body: { currency: '={{ $value }}' } } },
			},
			{
				displayName: 'Language',
				name: 'hl',
				type: 'string',
				default: 'en',
				description: 'UI language code (e.g. en, fr, de)',
				routing: { request: { body: { hl: '={{ $value }}' } } },
			},
		],
	},

	// ── Additional Options: News Search ──
	{
		displayName: 'Additional Options',
		name: 'additionalOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: { resource: ['google'], operation: ['newsSearch'] } },
		options: [
			{
				displayName: 'Country Code',
				name: 'gl',
				type: 'string',
				default: 'us',
				description: 'ISO 3166-1 alpha-2 country code (e.g. us, gb, fr)',
				routing: { request: { body: { gl: '={{ $value }}' } } },
			},
			{
				displayName: 'Google Domain',
				name: 'google_domain',
				type: 'string',
				default: 'google.com',
				description: 'Regional Google domain (e.g. google.com, google.de)',
				routing: { request: { body: { google_domain: '={{ $value }}' } } },
			},
			{
				displayName: 'Language',
				name: 'hl',
				type: 'string',
				default: 'en',
				description: 'UI language code (e.g. en, fr, de)',
				routing: { request: { body: { hl: '={{ $value }}' } } },
			},
			{
				displayName: 'Sort By',
				name: 'so',
				type: 'options',
				default: 0,
				description: 'Result order. Only valid when searching by Query or Entity.',
				options: [
					{ name: 'Relevance', value: 0 },
					{ name: 'Date', value: 1 },
				],
				routing: { request: { body: { so: '={{ $value }}' } } },
			},
		],
	},

	// ── Additional Options: Trends ──
	{
		displayName: 'Additional Options',
		name: 'additionalOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: { resource: ['google'], operation: ['trends'] } },
		options: [
			{
				displayName: 'Category',
				name: 'cat',
				type: 'string',
				default: '',
				placeholder: '71',
				description: 'Google Trends category ID',
				routing: { request: { body: { cat: '={{ $value }}' } } },
			},
			{
				displayName: 'Data Type',
				name: 'data_type',
				type: 'options',
				default: 'TIMESERIES',
				description: 'Which slice of the trends report to return',
				options: [
					{ name: 'Geo Map', value: 'GEO_MAP' },
					{ name: 'Geo Map 0', value: 'GEO_MAP_0' },
					{ name: 'Related Queries', value: 'RELATED_QUERIES' },
					{ name: 'Related Topics', value: 'RELATED_TOPICS' },
					{ name: 'Timeseries', value: 'TIMESERIES' },
				],
				routing: { request: { body: { data_type: '={{ $value }}' } } },
			},
			{
				displayName: 'Date Range',
				name: 'date',
				type: 'string',
				default: '',
				placeholder: 'today 12-m',
				description: 'Time range, e.g. "today 12-m" or "2025-01-01 2025-12-31"',
				routing: { request: { body: { date: '={{ $value }}' } } },
			},
			{
				displayName: 'Geo',
				name: 'geo',
				type: 'string',
				default: '',
				placeholder: 'US',
				description: 'Uppercase region code such as US, GB or US-CA. Worldwide when left empty.',
				routing: { request: { body: { geo: '={{ $value }}' } } },
			},
			{
				displayName: 'Language',
				name: 'hl',
				type: 'string',
				default: 'en',
				description: 'UI language code (e.g. en, fr, de)',
				routing: { request: { body: { hl: '={{ $value }}' } } },
			},
			{
				displayName: 'Property',
				name: 'gprop',
				type: 'options',
				default: 'news',
				description: 'Google property to measure interest on. Web search when left unset.',
				options: [
					{ name: 'Images', value: 'images' },
					{ name: 'News', value: 'news' },
					{ name: 'Shopping', value: 'froogle' },
					{ name: 'YouTube', value: 'youtube' },
				],
				routing: { request: { body: { gprop: '={{ $value }}' } } },
			},
			{
				displayName: 'Region',
				name: 'region',
				type: 'options',
				default: 'COUNTRY',
				description: 'Granularity of the interest-by-region breakdown',
				options: [
					{ name: 'City', value: 'CITY' },
					{ name: 'Country', value: 'COUNTRY' },
					{ name: 'DMA', value: 'DMA' },
					{ name: 'Region', value: 'REGION' },
				],
				routing: { request: { body: { region: '={{ $value }}' } } },
			},
			{
				displayName: 'Timezone Offset',
				name: 'tz',
				type: 'string',
				default: '',
				placeholder: '-120',
				description: 'Timezone offset in minutes, sent as a string',
				routing: { request: { body: { tz: '={{ $value }}' } } },
			},
		],
	},

	// ── Additional Options: Trending Now ──
	{
		displayName: 'Additional Options',
		name: 'additionalOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: { resource: ['google'], operation: ['trendingNow'] } },
		options: [
			{
				displayName: 'Category',
				name: 'cat',
				type: 'number',
				default: 0,
				typeOptions: { minValue: 0, maxValue: 20 },
				description: 'Category ID, 0 is all categories',
				routing: { request: { body: { cat: '={{ $value }}' } } },
			},
			{
				displayName: 'Hours',
				name: 'hours',
				type: 'number',
				default: 24,
				description: 'Trailing window in hours, typically 4, 24, 48 or 168',
				routing: { request: { body: { hours: '={{ $value }}' } } },
			},
			{
				displayName: 'Language',
				name: 'hl',
				type: 'string',
				default: 'en',
				description: 'UI language code (e.g. en, fr, de)',
				routing: { request: { body: { hl: '={{ $value }}' } } },
			},
			{
				displayName: 'Sort',
				name: 'sort',
				type: 'options',
				default: 'search_volume',
				options: [
					{ name: 'Recency', value: 'recency' },
					{ name: 'Relevance', value: 'relevance' },
					{ name: 'Search Volume', value: 'search_volume' },
					{ name: 'Title', value: 'title' },
				],
				routing: { request: { body: { sort: '={{ $value }}' } } },
			},
			{
				displayName: 'Status',
				name: 'status',
				type: 'options',
				default: 'active',
				description: 'Whether to include trends that have already cooled off',
				options: [
					{ name: 'Active', value: 'active' },
					{ name: 'All', value: 'all' },
				],
				routing: { request: { body: { status: '={{ $value }}' } } },
			},
		],
	},
];
