import type { INodeProperties } from 'n8n-workflow';

export const googleOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['google'] } },
		options: [
			{
				name: 'Search',
				value: 'search',
				action: 'Search google',
				description: 'Search Google and return organic results, knowledge graph, news, and more',
				routing: {
					request: { method: 'POST', url: '/api/v2/google' },
				},
			},
			{
				name: 'AI Mode',
				value: 'aiMode',
				action: 'Search google ai mode',
				description: "Ask Google's AI Mode and return its answer blocks, references, and shopping results",
				routing: {
					request: { method: 'POST', url: '/api/v2/google/ai-mode' },
				},
			},
			{
				name: 'Maps Search',
				value: 'mapsSearch',
				action: 'Search google maps',
				description: 'Search Google Maps and return local business listings with ratings, reviews, and contact details',
				routing: {
					request: { method: 'POST', url: '/api/v2/google/maps/search' },
				},
			},
		],
		default: 'search',
	},
];

export const googleFields: INodeProperties[] = [
	{
		displayName: 'Query',
		name: 'query',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'best running shoes 2026',
		displayOptions: { show: { resource: ['google'], operation: ['search', 'aiMode', 'mapsSearch'] } },
		routing: { request: { body: { query: '={{ $value }}' } } },
		description: 'The search query. For Maps Search use a niche plus a place, e.g. "plumbers in Austin, TX".',
	},
	{
		displayName: 'Additional Options',
		name: 'additionalOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: { resource: ['google'], operation: ['search'] } },
		options: [
			{
				displayName: 'Country Code',
				name: 'gl',
				type: 'string',
				default: 'us',
				description: 'ISO 3166-1 alpha-2 country code (e.g. us, gb, fr)',
				routing: { request: { body: { gl: '={{ $value }}' } } },
			},
			{
				displayName: 'Device',
				name: 'device',
				type: 'options',
				default: 'desktop',
				options: [
					{ name: 'Desktop', value: 'desktop' },
					{ name: 'Mobile', value: 'mobile' },
				],
				routing: { request: { body: { device: '={{ $value }}' } } },
			},
			{
				displayName: 'Google Domain',
				name: 'google_domain',
				type: 'string',
				default: 'google.com',
				description: 'Regional Google domain (e.g. google.com, google.de)',
				routing: { request: { body: { google_domain: '={{ $value }}' } } },
			},
			{
				displayName: 'Language',
				name: 'hl',
				type: 'string',
				default: 'en',
				description: 'UI language code (e.g. en, fr, de)',
				routing: { request: { body: { hl: '={{ $value }}' } } },
			},
			{
				displayName: 'Location',
				name: 'location',
				type: 'string',
				default: '',
				placeholder: 'New York,New York,United States',
				description: 'Canonical location name the search originates from',
				routing: { request: { body: { location: '={{ $value }}' } } },
			},
			{
				displayName: 'Page',
				name: 'page',
				type: 'number',
				default: 1,
				typeOptions: { minValue: 1, maxValue: 100 },
				description: 'Page number, 1-indexed',
				routing: { request: { body: { start: '={{ ($value - 1) * 10 }}' } } },
			},
			{
				displayName: 'Resolve AI Overview',
				name: 'resolve_ai_overview',
				type: 'boolean',
				default: true,
				description:
					'Whether to make the follow-up call and inline the full AI Overview when Google defers it. Enabled by default; turn off to skip that extra upstream request.',
				routing: { request: { body: { resolve_ai_overview: '={{ $value }}' } } },
			},
		],
	},
	{
		displayName: 'Additional Options',
		name: 'additionalOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: { resource: ['google'], operation: ['aiMode'] } },
		options: [
			{
				displayName: 'Country Code',
				name: 'gl',
				type: 'string',
				default: 'us',
				description: 'ISO 3166-1 alpha-2 country code (e.g. us, gb, fr)',
				routing: { request: { body: { gl: '={{ $value }}' } } },
			},
			{
				displayName: 'Device',
				name: 'device',
				type: 'options',
				default: 'desktop',
				options: [
					{ name: 'Desktop', value: 'desktop' },
					{ name: 'Mobile', value: 'mobile' },
				],
				routing: { request: { body: { device: '={{ $value }}' } } },
			},
			{
				displayName: 'Google Domain',
				name: 'google_domain',
				type: 'string',
				default: 'google.com',
				description: 'Regional Google domain (e.g. google.com, google.de)',
				routing: { request: { body: { google_domain: '={{ $value }}' } } },
			},
			{
				displayName: 'Language',
				name: 'hl',
				type: 'string',
				default: 'en',
				description: 'UI language code (e.g. en, fr, de)',
				routing: { request: { body: { hl: '={{ $value }}' } } },
			},
			{
				displayName: 'Location',
				name: 'location',
				type: 'string',
				default: '',
				placeholder: 'New York,New York,United States',
				description: 'Canonical location name the search originates from',
				routing: { request: { body: { location: '={{ $value }}' } } },
			},
			{
				displayName: 'Safe Search',
				name: 'safe',
				type: 'options',
				default: 'active',
				description: 'Filter adult content out of the results',
				options: [{ name: 'Active', value: 'active' }],
				routing: { request: { body: { safe: '={{ $value }}' } } },
			},
		],
	},
	{
		displayName: 'Additional Options',
		name: 'additionalOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: { resource: ['google'], operation: ['mapsSearch'] } },
		options: [
			{
				displayName: 'Country Code',
				name: 'gl',
				type: 'string',
				default: 'us',
				description: 'ISO 3166-1 alpha-2 country code (e.g. us, gb, fr)',
				routing: { request: { body: { gl: '={{ $value }}' } } },
			},
			{
				displayName: 'Google Domain',
				name: 'google_domain',
				type: 'string',
				default: 'google.com',
				description: 'Regional Google domain (e.g. google.com, google.de)',
				routing: { request: { body: { google_domain: '={{ $value }}' } } },
			},
			{
				displayName: 'Language',
				name: 'hl',
				type: 'string',
				default: 'en',
				description: 'UI language code (e.g. en, fr, de)',
				routing: { request: { body: { hl: '={{ $value }}' } } },
			},
			{
				displayName: 'Map Center',
				name: 'll',
				type: 'string',
				default: '',
				placeholder: '@30.2672,-97.7431,12z',
				description:
					'Map center as @lat,lng,zoomz. This, not Country Code, controls where results come from. Leave empty to default to the country centre.',
				routing: { request: { body: { ll: '={{ $value }}' } } },
			},
			{
				displayName: 'Start Offset',
				name: 'start',
				type: 'number',
				default: 0,
				typeOptions: { minValue: 0 },
				description: 'Result offset, in multiples of 20 (0, 20, 40, ...)',
				routing: { request: { body: { start: '={{ $value }}' } } },
			},
		],
	},
];
