import type { INodeProperties } from 'n8n-workflow';

export const walmartOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['walmart'] } },
		options: [
			{
				name: 'Search Products',
				value: 'search',
				action: 'Search walmart products',
				description: 'Search Walmart and return product listings',
				routing: { request: { method: 'POST', url: '/api/v1/walmart/search' } },
			},
			{
				name: 'Get Product',
				value: 'product',
				action: 'Get a walmart product',
				description: 'Get detailed information for a Walmart product by ID',
				routing: { request: { method: 'POST', url: '/api/v1/walmart/product' } },
			},
		],
		default: 'search',
	},
];

export const walmartFields: INodeProperties[] = [
	{
		displayName: 'Query',
		name: 'query',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'air fryer 6 quart',
		displayOptions: { show: { resource: ['walmart'], operation: ['search'] } },
		routing: { request: { body: { query: '={{ $value }}' } } },
		description: 'Product search query',
	},
	{
		displayName: 'Product ID',
		name: 'product_id',
		type: 'string',
		required: true,
		default: '',
		placeholder: '1234567890',
		displayOptions: { show: { resource: ['walmart'], operation: ['product'] } },
		routing: { request: { body: { product_id: '={{ $value }}' } } },
		description: 'Walmart product ID, the numeric string from the /ip/.../PRODUCT_ID URL',
	},
	{
		displayName: 'Additional Options',
		name: 'additionalOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: { resource: ['walmart'], operation: ['search'] } },
		options: [
			{
				displayName: 'Delivery ZIP',
				name: 'delivery_zip',
				type: 'string',
				default: '',
				placeholder: '78701',
				description: 'ZIP code the results are priced and stocked for',
				routing: { request: { body: { delivery_zip: '={{ $value }}' } } },
			},
			{
				displayName: 'Device',
				name: 'device',
				type: 'options',
				default: 'desktop',
				options: [
					{ name: 'Desktop', value: 'desktop' },
					{ name: 'Mobile', value: 'mobile' },
					{ name: 'Tablet', value: 'tablet' },
				],
				routing: { request: { body: { device: '={{ $value }}' } } },
			},
			{
				displayName: 'Domain',
				name: 'domain',
				type: 'string',
				default: 'walmart.com',
				description: 'Walmart domain to search',
				routing: { request: { body: { domain: '={{ $value }}' } } },
			},
			{
				displayName: 'Fulfillment Speed',
				name: 'fulfillment_speed',
				type: 'options',
				default: 'anytime',
				options: [
					{ name: 'Anytime', value: 'anytime' },
					{ name: 'Today', value: 'today' },
					{ name: 'Tomorrow', value: 'tomorrow' },
					{ name: '2 Days', value: '2_days' },
				],
				routing: { request: { body: { fulfillment_speed: '={{ $value }}' } } },
			},
			{
				displayName: 'Fulfillment Type',
				name: 'fulfillment_type',
				type: 'options',
				default: 'in_store',
				description: 'Restrict to items available for in-store pickup',
				options: [{ name: 'In Store', value: 'in_store' }],
				routing: { request: { body: { fulfillment_type: '={{ $value }}' } } },
			},
			{
				displayName: 'Max Price',
				name: 'max_price',
				type: 'number',
				default: 0,
				description: 'Maximum price in USD',
				routing: { request: { body: { max_price: '={{ $value }}' } } },
			},
			{
				displayName: 'Min Price',
				name: 'min_price',
				type: 'number',
				default: 0,
				description: 'Minimum price in USD',
				routing: { request: { body: { min_price: '={{ $value }}' } } },
			},
			{
				displayName: 'Sort By',
				name: 'sort_by',
				type: 'options',
				default: 'best_match',
				options: [
					{ name: 'Best Match', value: 'best_match' },
					{ name: 'Price: Low to High', value: 'price_low' },
					{ name: 'Price: High to Low', value: 'price_high' },
					{ name: 'Best Seller', value: 'best_seller' },
				],
				routing: { request: { body: { sort_by: '={{ $value }}' } } },
			},
			{
				displayName: 'Start Page',
				name: 'start_page',
				type: 'number',
				default: 1,
				typeOptions: { minValue: 1 },
				description: 'Result page to start from. This is the only Walmart pagination field.',
				routing: { request: { body: { start_page: '={{ $value }}' } } },
			},
			{
				displayName: 'Store ID',
				name: 'store_id',
				type: 'string',
				default: '',
				description: 'Walmart store ID to price and stock the results against',
				routing: { request: { body: { store_id: '={{ $value }}' } } },
			},
		],
	},
	{
		displayName: 'Additional Options',
		name: 'additionalOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: { resource: ['walmart'], operation: ['product'] } },
		options: [
			{
				displayName: 'Delivery ZIP',
				name: 'delivery_zip',
				type: 'string',
				default: '',
				placeholder: '78701',
				description: 'ZIP code the product is priced and stocked for',
				routing: { request: { body: { delivery_zip: '={{ $value }}' } } },
			},
			{
				displayName: 'Device',
				name: 'device',
				type: 'options',
				default: 'desktop',
				options: [
					{ name: 'Desktop', value: 'desktop' },
					{ name: 'Mobile', value: 'mobile' },
					{ name: 'Tablet', value: 'tablet' },
				],
				routing: { request: { body: { device: '={{ $value }}' } } },
			},
			{
				displayName: 'Domain',
				name: 'domain',
				type: 'string',
				default: 'walmart.com',
				description: 'Walmart domain to read the product from',
				routing: { request: { body: { domain: '={{ $value }}' } } },
			},
			{
				displayName: 'Store ID',
				name: 'store_id',
				type: 'string',
				default: '',
				description: 'Walmart store ID to price and stock the product against',
				routing: { request: { body: { store_id: '={{ $value }}' } } },
			},
		],
	},
];
