import type { INodeProperties } from 'n8n-workflow';

export const zillowOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['zillow'] } },
		options: [
			{
				name: 'Get Agent Reviews',
				value: 'agentReviews',
				action: 'Get zillow agent reviews',
				description:
					'Get a Zillow agent profile and reviews: rating, review count, bodies with sub-ratings, specialties, languages, licenses, service areas, sales counts. This addresses an AGENT by screen name, not a property, and Zillow server-renders only the first five bodies: count is what came back, total_review_count is what the agent has. Costs 1 credit.',
				routing: { request: { method: 'POST', url: '/api/v1/zillow/reviews' } },
			},
			{
				name: 'Get Property',
				value: 'property',
				action: 'Get a zillow property',
				description:
					'Get a full Zillow listing: price and price history, Zestimate, tax history, description, RESO facts, rooms, schools, open houses, photos, attribution. Rental buildings return floor plans, amenities and unit counts instead. Costs 1 credit.',
				routing: { request: { method: 'POST', url: '/api/v1/zillow/property' } },
			},
			{
				name: 'Search Listings',
				value: 'search',
				action: 'Search zillow listings',
				description:
					'Search Zillow listings in a region: price, beds, baths, living area, Zestimate, coordinates, images, days on market. A region Zillow cannot resolve comes back as a 404, not an empty result set. Costs 1 credit.',
				routing: { request: { method: 'POST', url: '/api/v1/zillow/search' } },
			},
		],
		default: 'search',
	},
];

export const zillowFields: INodeProperties[] = [
	// ── Search Listings ──
	{
		displayName: 'Location',
		name: 'location',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'Austin, TX',
		displayOptions: { show: { resource: ['zillow'], operation: ['search'] } },
		routing: { request: { body: { location: '={{ $value }}' } } },
		description:
			'Region as a Zillow slug, a city name, a ZIP or a pasted Zillow search URL. A bare ZIP works on its own but cannot be combined with any filter or sort, because Zillow geolocates that request shape and answers about another city; use the city name whenever you filter.',
	},

	// ── Get Property ──
	{
		displayName: 'Property ID',
		name: 'zpid',
		type: 'string',
		required: true,
		default: '',
		placeholder: '30771893',
		displayOptions: { show: { resource: ['zillow'], operation: ['property'] } },
		routing: { request: { body: { zpid: '={{ $value }}' } } },
		description:
			'Zillow zpid, a /homedetails/ URL, or a zillow.com/apartments/ building URL. Rental buildings have no caller-visible zpid because search returns coordinates in that slot, so pass the apartments URL for those.',
	},

	// ── Get Agent Reviews ──
	{
		displayName: 'Screen Name',
		name: 'screen_name',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'John Smith',
		displayOptions: { show: { resource: ['zillow'], operation: ['agentReviews'] } },
		routing: { request: { body: { screen_name: '={{ $value }}' } } },
		description:
			'Agent screen name from a zillow.com/profile/ URL, or the full profile URL; it may contain spaces',
	},

	// ── Additional Options: Search Listings ──
	{
		displayName: 'Additional Options',
		name: 'additionalOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: { resource: ['zillow'], operation: ['search'] } },
		options: [
			{
				displayName: '3D Tour',
				name: 'is_3d_tour',
				type: 'boolean',
				default: false,
				description: 'Whether to keep only listings with a 3D tour',
				routing: { request: { body: { is_3d_tour: '={{ $value }}' } } },
			},
			{
				displayName: 'Baths Max',
				name: 'baths_max',
				type: 'number',
				default: 0,
				description: 'Maximum bathrooms, half-baths allowed as 1.5',
				routing: { request: { body: { baths_max: '={{ $value }}' } } },
			},
			{
				displayName: 'Baths Min',
				name: 'baths_min',
				type: 'number',
				default: 0,
				description: 'Minimum bathrooms, half-baths allowed as 1.5',
				routing: { request: { body: { baths_min: '={{ $value }}' } } },
			},
			{
				displayName: 'Beds Max',
				name: 'beds_max',
				type: 'number',
				default: 0,
				description: 'Maximum bedrooms',
				routing: { request: { body: { beds_max: '={{ $value }}' } } },
			},
			{
				displayName: 'Beds Min',
				name: 'beds_min',
				type: 'number',
				default: 0,
				description: 'Minimum bedrooms',
				routing: { request: { body: { beds_min: '={{ $value }}' } } },
			},
			{
				displayName: 'Days on Zillow',
				name: 'days_on_zillow',
				type: 'options',
				default: '1',
				description:
					'How recently the listing appeared. This list is closed; an unrecognised value returns the unfiltered set under a 200 rather than an error.',
				options: [
					{ name: '1 Day', value: '1' },
					{ name: '7 Days', value: '7' },
					{ name: '14 Days', value: '14' },
					{ name: '30 Days', value: '30' },
					{ name: '90 Days', value: '90' },
					{ name: '6 Months', value: '6m' },
					{ name: '12 Months', value: '12m' },
					{ name: '24 Months', value: '24m' },
					{ name: '36 Months', value: '36m' },
				],
				routing: { request: { body: { days_on_zillow: '={{ $value }}' } } },
			},
			{
				displayName: 'Has Air Conditioning',
				name: 'has_air_conditioning',
				type: 'boolean',
				default: false,
				description: 'Whether to keep only listings with air conditioning',
				routing: { request: { body: { has_air_conditioning: '={{ $value }}' } } },
			},
			{
				displayName: 'Has Basement',
				name: 'has_basement',
				type: 'boolean',
				default: false,
				description: 'Whether to keep only listings with a basement',
				routing: { request: { body: { has_basement: '={{ $value }}' } } },
			},
			{
				displayName: 'Has Garage',
				name: 'has_garage',
				type: 'boolean',
				default: false,
				description: 'Whether to keep only listings with a garage',
				routing: { request: { body: { has_garage: '={{ $value }}' } } },
			},
			{
				displayName: 'Has Open House',
				name: 'has_open_house',
				type: 'boolean',
				default: false,
				description: 'Whether to keep only listings with an open house scheduled',
				routing: { request: { body: { has_open_house: '={{ $value }}' } } },
			},
			{
				displayName: 'Has Pool',
				name: 'has_pool',
				type: 'boolean',
				default: false,
				description: 'Whether to keep only listings with a pool',
				routing: { request: { body: { has_pool: '={{ $value }}' } } },
			},
			{
				displayName: 'Home Type',
				name: 'home_type',
				type: 'options',
				default: 'houses',
				description: 'Property type to keep',
				options: [
					{ name: 'Apartments', value: 'apartments' },
					{ name: 'Condos', value: 'condos' },
					{ name: 'Houses', value: 'houses' },
					{ name: 'Lots and Land', value: 'lots_land' },
					{ name: 'Manufactured', value: 'manufactured' },
					{ name: 'Multi-Family', value: 'multi_family' },
					{ name: 'Townhomes', value: 'townhomes' },
				],
				routing: { request: { body: { home_type: '={{ $value }}' } } },
			},
			{
				displayName: 'Keywords',
				name: 'keywords',
				type: 'string',
				default: '',
				placeholder: 'casita',
				description: 'Free-text keywords matched against the listing copy',
				routing: { request: { body: { keywords: '={{ $value }}' } } },
			},
			{
				displayName: 'Listing Status',
				name: 'listing_status',
				type: 'options',
				default: 'for_sale',
				description:
					'Which market to search. On For Rent, Min Price and Max Price mean MONTHLY RENT, because Zillow files rent under its payment filter rather than its price filter.',
				options: [
					{ name: 'For Rent', value: 'for_rent' },
					{ name: 'For Sale', value: 'for_sale' },
					{ name: 'Sold', value: 'sold' },
				],
				routing: { request: { body: { listing_status: '={{ $value }}' } } },
			},
			{
				displayName: 'Lot Size Max',
				name: 'lot_size_max',
				type: 'number',
				default: 0,
				description: 'Maximum lot size in square feet',
				routing: { request: { body: { lot_size_max: '={{ $value }}' } } },
			},
			{
				displayName: 'Lot Size Min',
				name: 'lot_size_min',
				type: 'number',
				default: 0,
				description: 'Minimum lot size in square feet',
				routing: { request: { body: { lot_size_min: '={{ $value }}' } } },
			},
			{
				displayName: 'Max HOA',
				name: 'max_hoa',
				type: 'number',
				default: 0,
				description: 'Maximum monthly HOA fee in USD',
				routing: { request: { body: { max_hoa: '={{ $value }}' } } },
			},
			{
				displayName: 'Max Price',
				name: 'max_price',
				type: 'number',
				default: 0,
				description:
					'Maximum price in USD, or maximum MONTHLY RENT when Listing Status is For Rent',
				routing: { request: { body: { max_price: '={{ $value }}' } } },
			},
			{
				displayName: 'Min Price',
				name: 'min_price',
				type: 'number',
				default: 0,
				description:
					'Minimum price in USD, or minimum MONTHLY RENT when Listing Status is For Rent',
				routing: { request: { body: { min_price: '={{ $value }}' } } },
			},
			{
				displayName: 'New Construction',
				name: 'is_new_construction',
				type: 'boolean',
				default: false,
				description: 'Whether to keep only new construction',
				routing: { request: { body: { is_new_construction: '={{ $value }}' } } },
			},
			{
				displayName: 'Page',
				name: 'page',
				type: 'number',
				default: 1,
				typeOptions: { minValue: 1 },
				description: 'Result page to read',
				routing: { request: { body: { page: '={{ $value }}' } } },
			},
			{
				displayName: 'Price Reduced',
				name: 'price_reduced',
				type: 'boolean',
				default: false,
				description: 'Whether to keep only listings with a price cut',
				routing: { request: { body: { price_reduced: '={{ $value }}' } } },
			},
			{
				displayName: 'Sort',
				name: 'sort',
				type: 'options',
				default: 'relevance',
				description:
					'Result sort order. Sorts that rank against a signed-in profile, such as saved, featured and personalised, are deliberately absent because we are never signed in.',
				options: [
					{ name: 'Baths', value: 'baths' },
					{ name: 'Beds', value: 'beds' },
					{ name: 'Lot Size', value: 'lot_size' },
					{ name: 'Newest', value: 'newest' },
					{ name: 'Payment: High to Low', value: 'payment_high' },
					{ name: 'Payment: Low to High', value: 'payment_low' },
					{ name: 'Price: High to Low', value: 'price_high' },
					{ name: 'Price: Low to High', value: 'price_low' },
					{ name: 'Recent Price Change', value: 'recent_change' },
					{ name: 'Recommended', value: 'recommended' },
					{ name: 'Relevance', value: 'relevance' },
					{ name: 'Square Feet', value: 'sqft' },
					{ name: 'Zestimate: High to Low', value: 'zestimate_high' },
					{ name: 'Zestimate: Low to High', value: 'zestimate_low' },
				],
				routing: { request: { body: { sort: '={{ $value }}' } } },
			},
			{
				displayName: 'Sqft Max',
				name: 'sqft_max',
				type: 'number',
				default: 0,
				description: 'Maximum living area in square feet',
				routing: { request: { body: { sqft_max: '={{ $value }}' } } },
			},
			{
				displayName: 'Sqft Min',
				name: 'sqft_min',
				type: 'number',
				default: 0,
				description: 'Minimum living area in square feet',
				routing: { request: { body: { sqft_min: '={{ $value }}' } } },
			},
			{
				displayName: 'Waterfront',
				name: 'is_waterfront',
				type: 'boolean',
				default: false,
				description: 'Whether to keep only waterfront listings',
				routing: { request: { body: { is_waterfront: '={{ $value }}' } } },
			},
			{
				displayName: 'Year Built Max',
				name: 'year_built_max',
				type: 'number',
				default: 0,
				description: 'Latest year built',
				routing: { request: { body: { year_built_max: '={{ $value }}' } } },
			},
			{
				displayName: 'Year Built Min',
				name: 'year_built_min',
				type: 'number',
				default: 0,
				description: 'Earliest year built',
				routing: { request: { body: { year_built_min: '={{ $value }}' } } },
			},
		],
	},
];
